/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/setup-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_auth_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup Admin */
        post: operations["setup_admin_api_v1_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Robots */
        get: operations["list_robots_api_v1_robots_get"];
        put?: never;
        /** Create Robot */
        post: operations["create_robot_api_v1_robots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Robot */
        get: operations["get_robot_api_v1_robots__robot_id__get"];
        put?: never;
        post?: never;
        /** Delete Robot */
        delete: operations["delete_robot_api_v1_robots__robot_id__delete"];
        options?: never;
        head?: never;
        /** Patch Robot */
        patch: operations["patch_robot_api_v1_robots__robot_id__patch"];
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Robot */
        post: operations["probe_robot_api_v1_robots__robot_id__probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telemetry */
        get: operations["telemetry_api_v1_robots__robot_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Episodes */
        get: operations["list_episodes_api_v1_robots__robot_id__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/episodes/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Episodes */
        post: operations["scan_episodes_api_v1_robots__robot_id__episodes_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episode_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Sync */
        post: operations["queue_sync_api_v1_episodes__episode_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sync Jobs */
        get: operations["list_sync_jobs_api_v1_sync_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Sync */
        post: operations["cancel_sync_api_v1_sync_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collections */
        get: operations["list_collections_api_v1_robots__robot_id__collections_get"];
        put?: never;
        /** Start Collection */
        post: operations["start_collection_api_v1_robots__robot_id__collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/camera-previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Camera Previews */
        get: operations["list_camera_previews_api_v1_robots__robot_id__camera_previews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/camera-previews/{channel}/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Camera Preview */
        get: operations["read_camera_preview_api_v1_robots__robot_id__camera_previews__channel__frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/camera-previews/{channel}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Camera Preview */
        get: operations["stream_camera_preview_api_v1_robots__robot_id__camera_previews__channel__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Collection */
        post: operations["stop_collection_api_v1_collections__collection_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/force-stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force Stop Collection */
        post: operations["force_stop_collection_api_v1_collections__collection_id__force_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/preview/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Collection Preview */
        get: operations["read_collection_preview_api_v1_collections__collection_id__preview__channel__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Collection */
        post: operations["decide_collection_api_v1_collections__collection_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/robots/{robot_id}/control-leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire Lease */
        post: operations["acquire_lease_api_v1_robots__robot_id__control_leases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Commands */
        get: operations["list_commands_api_v1_commands_get"];
        put?: never;
        /** Queue Command */
        post: operations["queue_command_api_v1_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditResponse */
        AuditResponse: {
            /** Id */
            id: string;
            /** Robot Id */
            robot_id: string | null;
            /** Action */
            action: string;
            /** Target */
            target: string;
            /** Request Payload */
            request_payload: {
                [key: string]: unknown;
            };
            /** Result Payload */
            result_payload: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuthResponse */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            /** Csrf Token */
            csrf_token: string;
        };
        /** CameraPreviewResponse */
        CameraPreviewResponse: {
            /** Channel */
            channel: string;
            /** Label */
            label: string;
            /** Captured At */
            captured_at: string | null;
            /** Age Ms */
            age_ms: number | null;
            /** Size */
            size: number | null;
            /** Stale */
            stale: boolean;
            /** Frame Url */
            frame_url: string;
            /** Stream Url */
            stream_url: string | null;
        };
        /** CollectionDecisionRequest */
        CollectionDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "keep" | "delete";
            /** Password */
            password?: string | null;
            /** Confirm Uid */
            confirm_uid?: string | null;
        };
        /** CollectionResponse */
        CollectionResponse: {
            /** Id */
            id: string;
            /** Robot Id */
            robot_id: string;
            /** Name */
            name: string;
            /** Task Id */
            task_id: number;
            /** Job Id */
            job_id: number;
            /** Record Uid */
            record_uid: string | null;
            /** Planned Duration Seconds */
            planned_duration_seconds: number | null;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Review Status */
            review_status: string;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Due At */
            due_at: string | null;
            /** Stopped At */
            stopped_at: string | null;
        };
        /** CollectionStartRequest */
        CollectionStartRequest: {
            /** Name */
            name: string;
            /** Planned Duration Seconds */
            planned_duration_seconds?: number | null;
        };
        /** CommandRequest */
        CommandRequest: {
            /** Robotid */
            robotId: string;
            /** Type */
            type: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Idempotencykey */
            idempotencyKey: string;
            /** Expectedrevision */
            expectedRevision: number;
            /** Controlleaseid */
            controlLeaseId: string;
        };
        /** CommandResponse */
        CommandResponse: {
            /** Id */
            id: string;
            /** Robot Id */
            robot_id: string;
            /** Command Type */
            command_type: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Idempotency Key */
            idempotency_key: string;
            /** Expected Revision */
            expected_revision: number;
            /** Status */
            status: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** EpisodeResponse */
        EpisodeResponse: {
            /** Id */
            id: string;
            /** Robot Id */
            robot_id: string;
            /** Uid */
            uid: string;
            /** Source Path */
            source_path: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Channels */
            channels: string[];
            /** File Size */
            file_size: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Aligned */
            aligned: boolean;
            /** Validation Status */
            validation_status: string;
            /** Sync Status */
            sync_status: string;
            /**
             * Last Scanned At
             * Format: date-time
             */
            last_scanned_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaseRequest */
        LeaseRequest: {
            /** Password */
            password: string;
            /** Physical Safety Confirmed */
            physical_safety_confirmed: boolean;
        };
        /** LeaseResponse */
        LeaseResponse: {
            /** Id */
            id: string;
            /** Robot Id */
            robot_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ProbeResponse */
        ProbeResponse: {
            /** Online */
            online: boolean;
            /** Capabilities */
            capabilities: string[];
            /** Status */
            status: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
        };
        /** RobotCreate */
        RobotCreate: {
            /** Name */
            name: string;
            /**
             * Model
             * @default Unknown
             */
            model: string;
            /**
             * Adapter Type
             * @enum {string}
             */
            adapter_type: "simulator" | "a2d";
            /** Connection */
            connection?: {
                [key: string]: unknown;
            };
            /**
             * Observe Only
             * @default true
             */
            observe_only: boolean;
            /** Enabled Commands */
            enabled_commands?: string[];
        };
        /** RobotPatch */
        RobotPatch: {
            /** Name */
            name?: string | null;
            /** Model */
            model?: string | null;
            /** Connection */
            connection?: {
                [key: string]: unknown;
            } | null;
            /** Observe Only */
            observe_only?: boolean | null;
            /** Enabled Commands */
            enabled_commands?: string[] | null;
        };
        /** RobotResponse */
        RobotResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Model */
            model: string;
            /** Adapter Type */
            adapter_type: string;
            /** Connection Summary */
            connection_summary?: {
                [key: string]: unknown;
            };
            /** Capabilities */
            capabilities: string[];
            /** Status */
            status: {
                [key: string]: unknown;
            };
            /** Online */
            online: boolean;
            /** Last Seen */
            last_seen: string | null;
            /** Revision */
            revision: number;
            /** Observe Only */
            observe_only: boolean;
            /** Enabled Commands */
            enabled_commands: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SetupRequest */
        SetupRequest: {
            /** Bootstrap Token */
            bootstrap_token: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** SetupStatus */
        SetupStatus: {
            /** Setup Required */
            setup_required: boolean;
        };
        /** SyncJobResponse */
        SyncJobResponse: {
            /** Id */
            id: string;
            /** Robot Id */
            robot_id: string;
            /** Episode Id */
            episode_id: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Target Path */
            target_path: string | null;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** TelemetryResponse */
        TelemetryResponse: {
            /** Id */
            id: string;
            /** Robot Id */
            robot_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    setup_status_api_v1_auth_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    setup_admin_api_v1_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_robots_api_v1_robots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_robot_api_v1_robots_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_robot_api_v1_robots__robot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_robot_api_v1_robots__robot_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_robot_api_v1_robots__robot_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobotPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_robot_api_v1_robots__robot_id__probe_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telemetry_api_v1_robots__robot_id__telemetry_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episodes_api_v1_robots__robot_id__episodes_get: {
        parameters: {
            query?: {
                aligned?: boolean | null;
                validation?: string | null;
                syncStatus?: string | null;
            };
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_episodes_api_v1_robots__robot_id__episodes_scan_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_sync_api_v1_episodes__episode_id__sync_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                episode_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sync_jobs_api_v1_sync_jobs_get: {
        parameters: {
            query?: {
                robot_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_sync_api_v1_sync_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_api_v1_robots__robot_id__collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_collection_api_v1_robots__robot_id__collections_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_camera_previews_api_v1_robots__robot_id__camera_previews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraPreviewResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_camera_preview_api_v1_robots__robot_id__camera_previews__channel__frame_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
                channel: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_camera_preview_api_v1_robots__robot_id__camera_previews__channel__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
                channel: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_collection_api_v1_collections__collection_id__stop_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                collection_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_stop_collection_api_v1_collections__collection_id__force_stop_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                collection_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_collection_preview_api_v1_collections__collection_id__preview__channel__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: string;
                channel: string;
            };
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_collection_api_v1_collections__collection_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                collection_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_lease_api_v1_robots__robot_id__control_leases_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                robot_id: string;
            };
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commands_api_v1_commands_get: {
        parameters: {
            query?: {
                robot_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_command_api_v1_commands_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
                openroboops_csrf?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                robot_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                openroboops_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
